### PR TITLE
Revert "feat: upgrade to shadow root v1"

### PR DESCRIPTION
**Pull request by manekinekko**
Reverts manekinekko/angular-wc-interop#2

### CODE REVIEW

**Comment by juristr** [comment]
ya...just seen that the v1 api hasn't been implemented in firefox etc..yet. Sorry :sweat_smile: 

http://caniuse.com/#feat=shadowdomv1

**Comment by manekinekko** [comment]
@juristr are you able to push the rest of changes. V1 specs require more changes: https://developers.google.com/web/fundamentals/getting-started/primers/customelements ?

**Comment by manekinekko** [comment]
Just in case, there is also this issue: https://github.com/manekinekko/angular-wc-interop/issues/1

**Comment by juristr** [comment]
Ok :smile:. But what additions are needed for custome elements v1? The main probl I see is that apparently the v1 spec of the shadow dom I've submitted in the PR isn't working in Firefox yet...at least I cannot get it running atm.

**Comment by juristr** [comment]
> @juristr are you able to push the rest of changes? V1 specs require more changes sadly :(

Have to do some other stuff first. Added to todo list and I'll come back later.

**Comment by manekinekko** [comment]
I'm tracking down the upgrade to v1 here: https://github.com/manekinekko/angular-wc-interop/issues/4

**Pull request closed without merging**
